#!/bin/bash
IMAGE_TAG=`date "+%Y-%m-%d_%H-%M"`

for CONTAINER in $( docker ps -q )
do
    CONTAINER_NAME=`docker inspect --format '{{.Name}}' $CONTAINER | sed "s,/,,g"`

    if docker image ls | grep -q "${CONTAINER_NAME}\s*${IMAGE_TAG}"
    then
        echo "Image Exist"
    else
        docker commit  $CONTAINER_NAME ${CONTAINER_NAME}:${IMAGE_TAG} >> /dev/null
        docker save ${CONTAINER_NAME}:${IMAGE_TAG} -o /tmp/scripts/${CONTAINER_NAME}:${IMAGE_TAG}.tar
    fi

done

find /tmp/scripts/  -mtime +1 -delete
